[2025-06-15T19:42:17.422+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-15T19:42:17.438+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: from_csv_to_pg.normalize_and_insert manual__2025-06-15T19:42:14.466843+00:00 [queued]>
[2025-06-15T19:42:17.444+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: from_csv_to_pg.normalize_and_insert manual__2025-06-15T19:42:14.466843+00:00 [queued]>
[2025-06-15T19:42:17.444+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-06-15T19:42:17.454+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): normalize_and_insert> on 2025-06-15 19:42:14.466843+00:00
[2025-06-15T19:42:17.460+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=164) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-15T19:42:17.462+0000] {standard_task_runner.py:72} INFO - Started process 166 to run task
[2025-06-15T19:42:17.462+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'from_csv_to_pg', 'normalize_and_insert', 'manual__2025-06-15T19:42:14.466843+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/from_csv_to_postgre.py', '--cfg-path', '/tmp/tmpk9mfidd2']
[2025-06-15T19:42:17.464+0000] {standard_task_runner.py:105} INFO - Job 66: Subtask normalize_and_insert
[2025-06-15T19:42:17.657+0000] {task_command.py:467} INFO - Running <TaskInstance: from_csv_to_pg.normalize_and_insert manual__2025-06-15T19:42:14.466843+00:00 [running]> on host 19a85dc332e9
[2025-06-15T19:42:17.718+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='from_csv_to_pg' AIRFLOW_CTX_TASK_ID='normalize_and_insert' AIRFLOW_CTX_EXECUTION_DATE='2025-06-15T19:42:14.466843+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-15T19:42:14.466843+00:00'
[2025-06-15T19:42:17.719+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-06-15T19:42:17.743+0000] {warnings.py:112} WARNING - /opt/***/dags/from_csv_to_postgre.py:23: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(raw_data, orient='records')

[2025-06-15T19:42:17.764+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-06-15T19:42:17.765+0000] {base.py:84} INFO - Retrieving connection 'dwh_***'
[2025-06-15T19:42:18.146+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/from_csv_to_postgre.py", line 161, in transform_and_load
    cursor.execute("""
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "sales_pkey"
DETAIL:  Key (invoice_id)=(750-67-8428) already exists.

[2025-06-15T19:42:18.154+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=from_csv_to_pg, task_id=normalize_and_insert, run_id=manual__2025-06-15T19:42:14.466843+00:00, execution_date=20250615T194214, start_date=20250615T194217, end_date=20250615T194218
[2025-06-15T19:42:18.174+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-06-15T19:42:18.175+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 66 for task normalize_and_insert (duplicate key value violates unique constraint "sales_pkey"
DETAIL:  Key (invoice_id)=(750-67-8428) already exists.
; 166)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/from_csv_to_postgre.py", line 161, in transform_and_load
    cursor.execute("""
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "sales_pkey"
DETAIL:  Key (invoice_id)=(750-67-8428) already exists.

[2025-06-15T19:42:18.198+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-15T19:42:18.347+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-15T19:42:18.348+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
